### ISSUE TITLE
Can't send embeds for LevelUpAnnouncement message

### ISSUE THREAD

**Issue by DevInfinix** [Defxult/discordLevelingSystem#1]
Hey @Defxult !
I would like to suggest a method by which we can send embeds for `LevelUpAnnounecment` message.

And can you please provide the link for your Discord Server if you have so that we can get help from others using this Library too :)

Thank you.

> (Discord : INFINIX#7276)

**Comment by Defxult** [comment]
That's a good idea! 😀 Keep an eye out on the repo, I'll add that feature to the library within the next couple days. It will only be on Github for a little while though, maybe a week or so then I'll upload it to PyPI. You can always install the Github version when I release it if you don't want to wait for the PyPI release.

As for the Discord server, I don't have one for the library at the moment because there isn't enough traffic to do so.
