### ISSUE TITLE
Level per XP

### ISSUE THREAD

**Issue by ShirkavandDev** [Defxult/discordLevelingSystem#6]
Hello !
I just wanted to know how do I set a maximum xp for each level?
for example 100 XP for 1 Level

**Comment by Defxult** [comment]
Changing that via the library isn't supported because that's not something MEE6 does. It is possible though. You'd have to go into `levels_xp_needed.py` and change all values in the `LEVELS_AND_XP` dictionary and set a maximum xp for each level to what you'd like that way. IIRC, there's nothing hard coded when it comes to `LEVELS_AND_XP`, so changing the values in that dictionary *shouldn't* cause any issues.
