### ISSUE TITLE
Feature request: Level promotion (json to database)

### ISSUE THREAD

**Issue by SaviorKnight** [Defxult/discordLevelingSystem#7]
Hi @Defxult,

First of thank you for sharing this awesome set of levelling tools.
I would like to ask if it would it be possible to add level promotion, what I mean by this at each level cap the experience accumulations stops until a faction to 'promote' a user is called. 

Example:
- Level 0 to 1 is 100 xp
- When user reaches 100 xp, xp accumulation stops for that user and 'locks' them to level 0 with 100xp
- Then when an 'unlock'/promote function is called the level up from 0 to 1 is granted and the level up message is send.

In my mind it would be an setting that skips automated advancement of the user and lets that behaviour be decided outside the library.

I hope it is something that can be added as it would save me allot of time having to start a level system from scratch.

**Comment by Defxult** [comment]
That’s not something that would be implemented because that would require the library to remember (have a value stored in the database file) who was pending a `/promote`. Which means a new row would have to be added to the database table, which is massively breaking and another `transfer()` method would have to be made. I guess the other way would be to have some type of pending pool (just a `list` of people waiting to receive a `/promote`, but I don’t think that’s ideal because on bot restart or cog reload that information would be lost. 

You said you’d have to start a leveling system from scratch, so I’m assuming you already have one? A json file maybe?

**Comment by SaviorKnight** [comment]
I can fully understand it was also a bit of a long shot to ask. I currently have a very basic xp system that ranks just on xp without levels. And it indeed stores this in json files but the rewrite would use a database to later expose the ranking on a web page as well to gain additional xp there. This change came about as I wanted to introduce tasks/challenges at thresholds that could be unlocked by doing certain actions (think be active in voice for 10 minutes or post on the site).

I however thought it could be done purely in code by adding a check if a certain parameter was set on creating the LevelingSystem that would block at every level xp limit and would only add xp again once that limit has passed.
So then the external code would check the `/promote` command conditions and call `award_xp` function again but with an optional `allowLevelUp` as a parameter.

I agree not a really clean way but it was a thought on how it could be done without any breaking changes, if you think this may be an addition I would be very thankful but I can fully understand if you would like to close the request.

Thank you again for this library

**Comment by Defxult** [comment]
I see. It's funny that you submitted this issue today because yesterday I thought it would be cool if people could somehow transfer their current leveling system information (their currently using a json file as their database) into my library's database file. But as I was thinking about it I had some difficulties on how I would implement it. It is possible though and would be a nice feature considering a lot of people watch those leveling system tutorials on YouTube which pretty much all are using json files for their system. Tell you what, I'll try and come up with an efficient way to implement that feature, if I'm successful, I'll ping you here to let you know that it's been implemented. If not, the labels that I have attached to this issue will be removed upon close.

**Comment by SaviorKnight** [comment]
Thank you.

**Comment by Defxult** [comment]
@SaviorKnight I've done my rounds of testing and seems to work well. You can find the documentation for it [here](https://github.com/Defxult/discordLevelingSystem#inserting-your-own-leveling-system-information) . If you (or anyone else that reads this issue) runs into any problems, please don't hesitate to report it. Thanks!
